server:
  port: 3333

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://wit-hackerthon2.cpadiqsprb8b.ap-northeast-2.rds.amazonaws.com:3306/exercise
    username: jimin
    password: rejin0421
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: update
      show-sql: 'true'
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        show-sql: true
    show-sql: true

